### ISSUE TITLE
smiley pix not displayed

### ISSUE THREAD

**Issue by ak4t0sh** [luukverhoeven/moodle-mod_gcanvas#1]
In [templates/canvas_emoji.mustache#L23](https://github.com/MFreakNL/moodle-mod_gcanvas/blob/418d531f285c14fe1b5e084a9bfd36770da3778d/templates/canvas_emoji.mustache#L23) your src URL are in absolute form. If Moodle (eg : https://mydomain.tld/moodle) is in a subdirectory pix are not displayed.

You should use [pix icon helper](https://docs.moodle.org/dev/Templates#.7B.7B.23_pix_.7D.7D) instead.

**Comment by luukverhoeven** [comment]
Thanks for reviewing the plugin! 

I added {{wwwroot}} instead and moved the emoji to a folder called emoji. For as far as I know, pix icon helper does not support / pix / subdirectory / icon. I don't want all emoji in the pix directory directly.

**Comment by ak4t0sh** [comment]
Thanks for your reactivity. Works for me :)

**Comment by ak4t0sh** [comment]
1f641.png (used in [templates/canvas_emoji.mustache#L101](https://github.com/MFreakNL/moodle-mod_gcanvas/blob/36562a3e64c83d189472a145a668f6dac2520aba/templates/canvas_emoji.mustache#L101)) seems to be missing

**Comment by luukverhoeven** [comment]
Removed from `canvas_emoji` 1 emoji less, there will be enough left ;)
