### ISSUE TITLE
Oplevering Moodle 4.2 + PHP 8.0

### ISSUE THREAD

**Issue by luukverhoeven** [luukverhoeven/moodle-mod_gcanvas#14]
Graag informeren wij jullie over de oplevering van de Moodle plug-in(s) en eventuele aanpassingen die jullie hebben aangevraagd. Zouden jullie de functionaliteit ervan kunnen controleren en nagaan of alles naar verwachting werkt? Eventuele vragen of opmerkingen vernemen wij graag.

Bijgevoegd vinden jullie de links naar de repositories:

https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/tree/86bwwnb0j-MOODLE42

Na jullie testen zien we graag jullie akkoord tegemoet voor het doorvoeren van de wijzigingen naar de main/master branch.

**Comment by gemguardian** [comment]
@luukverhoeven - Ik dacht dit ook PHP 8. 1 zou worden?

Ik heb het getest in M4.2 / PHP 8.1

1. Wanneer ik als student het canvas wil bewaren gebeurd er niets. 
2. Wanneer ik een afbeelding upload en klik op Uploaden gebeurd er niets. 
3. Wanneer ik op de "smiley' klik gebeurd er niets 

Zouden jullie dit aub nog even goed kunnen nalopen en controleren? Dit heeft altijd gewerkt.

**Comment by luukverhoeven** [comment]
@vincentcornelis Kun je dit bekijken onderzoeken? @gemguardian Wat betreft de PHP-versie `8.0` of `8.1` is geen groot verschil en werkt verwacht ik ook. Vincent had je het op `8.1` of `8.0` getest? Ik had de PHP-versie volgens mij uit de mail overgenomen.

**Comment by vincentcornelis** [comment]
@gemguardian 

Staat een nieuwe versie klaar om te testen voor het opslaan van het canvas, en het laden van afbeeldingen / smileys:
https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/tree/86bwwnb0j-MOODLE42

We hadden de plug-in al getest op 8.0 én 8.1, dit blijft onveranderd.

**Comment by gemguardian** [comment]
@vincentcornelis bedankt - werkt weer goed op 4.2! je kan deze versie de nieuwe main maken (Graag de huidige in een aparte branche zetten). Kun je meteen zorgen dat he top Moodle.org terecht komt? 

Dank!

**Comment by luukverhoeven** [comment]
@gemguardian Doorgezet, ook uitgerold op Moodle.org
