### ISSUE TITLE
Moodle 4.3 - release

### ISSUE THREAD

**Issue by luukverhoeven** [luukverhoeven/moodle-mod_gcanvas#17]
Hi Gemma, we have updated the plugin for Moodle 4.3 in a separate branch. 
https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/tree/86by49r4k-MOODLE43

Can you confirm it works as expected? After this, I will merge it to master branch.

**Comment by gemguardian** [comment]
@luukverhoeven ziet er goed uit. Graag beschikbaar maken voor Moodle.org - ik ga 4.4 deze week nog testen.

**Comment by luukverhoeven** [comment]
@gemguardian  Doorgezet
