### ISSUE TITLE
Canvas icoontje vervangen

### ISSUE THREAD

**Issue by gemguardian** [luukverhoeven/moodle-mod_gcanvas#18]
![canvas](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/assets/16559999/962bfc2c-94b1-47f8-a88e-8ff49199091a)
@luukverhoeven ze hebben nieuw icoontjes in 4.4 ik zou graag Canvas hierin mee willen laten gaan. Zie bijlage , kun je daar iets mee? 
Als je een ander file type of format nodig hebt dan hoor ik het graag want dan ga ik kijken wat ik door Monique kan laten maken.

**Comment by luukverhoeven** [comment]
@gemguardian  Deze moet in plaats van deze denk ik?
![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/assets/995760/94dcaf1e-25c5-4ea3-9473-445847808d05)

Heb je ook iets meer vierkant? 1:1

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/assets/995760/9a158b7a-e492-45ad-9367-e13010b2e02b)

**Comment by gemguardian** [comment]
![LTNC plugin images (3)](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/assets/16559999/5f14fb56-a993-4144-8f09-743b13da0ef0)
![LTNC plugin images](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/assets/16559999/37ca8638-beac-4809-9c93-c7a9459be210)

Dat is inderdaad wat ik bedoelde. zou een van deze werken? 
![palette-solid](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/assets/16559999/bae199f1-7530-4716-bb99-09fc703f1eaf)

**Comment by luukverhoeven** [comment]
@gemguardian In de master branch gezet. Kun je kijken of naar wens is?

**Comment by gemguardian** [comment]
@luukverhoeven deels ja, maar nu wilde ik ook dat de kleur wijzigde omdat er een purpose https://componentlibrary.moodle.com/admin/tool/componentlibrary/docspage.php/moodle/components/activityicons/#examplesaan gegeven was. Ik heb zelf wat zitten spelen en het is mij gelukt. 

ZOu wel fijn zijn als jij ook nog even kan kijken of het zo goed is gedaan. Ik zag op mijn omgeving verder niets bijzonders meer. 

Het betreft aanpassing in de Lib.php file en hernoeming van icon.svg naar monologo.svg

**Comment by luukverhoeven** [comment]
@gemguardian Alleen codestyle aangepast. Had dit nog niet gezien en/of gebruikt :) Goed gevonden!
Verder werkt prima. 

![image](https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/assets/995760/87ad7019-ed70-4ab5-b896-1756d1725c30)

**Comment by gemguardian** [comment]
@luukverhoeven super :) Zou jij de merging naar master en push naar Moodle.org willen doen? zeker dat laatste heb ik het idee dat ik dit ontzettend moeilijk maak. Maar als je een korte handleiding schrijft dan kan ik dat vast zelf volgende keer.

**Comment by luukverhoeven** [comment]
@gemguardian Dit heb ik zojuist gedaan. Hierbij een how-to mocht je dit zelf een keer willen uitvoeren. 


https://www.dropbox.com/scl/fi/d7a7mpxq7yyzcp76exby9/2024-05-10_15-44-14.mp4?rlkey=ec5t3fxjworz0s8x2plohiykp&dl=0
