### ISSUE TITLE
Moodle 4.5 release

### ISSUE THREAD

**Issue by luukverhoeven** [luukverhoeven/moodle-mod_gcanvas#19]
Hi @gemguardian @servicedeskltnc,

We would like to inform you about the delivery of the Moodle plugin and any adjustments you have requested. 
Please check their functionality and verify if everything is working as expected. We would appreciate hearing any questions or comments you might have.

Attached you will find the links to the repositories:

https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/tree/86by49k6p-upgrade-moodle45

After your testing, we look forward to receiving your approval to proceed with applying the changes to the main/master branch.

**Comment by wbuk** [comment]
I have installed Moodle 4.5, and some features, such as the buttons, do not work.  The save button does not work.  The HELP buttons do not work.  Students can type text though.

Please also consider adding the setting to allow us to rename the HELP button to INSTRUCTIONS  or TASK.
I may have been a bit quick updating to 4.5 as this plugin no longer works.  Cheers.

**Comment by gemguardian** [comment]
@wbuk I quickly tested the version in the link above and the save button does work. We are going to finish are test this week. 

You can change the text HELP to what you want by change the language file at Moodle language. Tag 
btn:help

**Comment by servicedeskltnc** [comment]
@luukverhoeven We have tested the newest version and all functionalities work again, could this upgrade be implemented on the main/master branch? Thanks in advance!

**Comment by gemguardian** [comment]
@vincentcornelis  ik tag jouw ook even. Vergeten jullie niet om de huidige main te verplaatsen naar een aparte branch én door te sturen naar Moodle Plugin database? Bedankt!

**Comment by luukverhoeven** [comment]
@gemguardian Merged. Save the original `MAIN` as a separate `MOODL44` branch, and proceed to publish the latest version on Moodle.org.
