### ISSUE TITLE
language pack

### ISSUE THREAD

**Issue by ak4t0sh** [luukverhoeven/moodle-mod_gcanvas#3]
The NL pack could be eventually moved away and submitted to AMOS.

https://lang.moodle.org/
https://docs.moodle.org/dev/AMOS_manual

please note - this is not a blocker for approval in the plugins db but would be nice to add at some point.

**Comment by luukverhoeven** [comment]
@gemguardian do you know how this process works?

**Comment by gemguardian** [comment]
@luukverhoeven I know how I can make changes to the language packs in AMOS.

**Comment by luukverhoeven** [comment]
Solved
