### ISSUE TITLE
css collisions

### ISSUE THREAD

**Issue by ak4t0sh** [luukverhoeven/moodle-mod_gcanvas#4]
To prevent collisions with other plugins you should always specify your CSS selectors in styles.css
see : https://docs.moodle.org/dev/Plugin_contribution_checklist#CSS_styles

**Comment by luukverhoeven** [comment]
Prefixed all css
https://github.com/MFreakNL/moodle-mod_gcanvas/blob/master/styles.css

**Comment by ak4t0sh** [comment]
Awesome Thanks :)
