### ISSUE TITLE
emoji license

### ISSUE THREAD

**Issue by ak4t0sh** [luukverhoeven/moodle-mod_gcanvas#5]
You have an huge emoji DB, where did they come from ? What is their license ?

**Comment by luukverhoeven** [comment]
The emoji coming from: https://github.com/twitter/twemoji

Does I need to add this license to the readme?
-
Graphics licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/

**Comment by ak4t0sh** [comment]
Based on https://docs.moodle.org/dev/Plugin_contribution_checklist#Licensing 

> Additional files contained in the plugin ZIP package (such as third party libraries used by the plugin, or included media) may eventually use other license as long as it is GPL compatible. See Plugin files#thirdpartylibs.xml for how to do it.

I think you should declare the pix/emoji/ folder as a thirdpartylib : https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

**Comment by luukverhoeven** [comment]
Added to the latest version of [thirdpartylibs.xml](https://github.com/MFreakNL/moodle-mod_gcanvas/blob/master/thirdpartylibs.xml)

**Comment by ak4t0sh** [comment]
Thanks ! Could you update the package on Moodle plugin DB please ? Once done ping me I'll send my review report and send it to david for final approval.

**Comment by luukverhoeven** [comment]
@ak4t0sh I added the latest version to moodle.org https://moodle.org/plugins/mod_gcanvas

**Comment by ak4t0sh** [comment]
Tracker updated. Thanks for your patience and reactivity @luukverhoeven  :+1:
