### ISSUE TITLE
Moodle 4.0/Boost en Classic issue: Showing Description activity double

### ISSUE THREAD

**Issue by gemguardian** [luukverhoeven/moodle-mod_gcanvas#9]
De activiteitsomschrijving wordt 2x getoond. Dit gebeurd alleen bij de standaard thema's Boost en Classic. 

![image](https://user-images.githubusercontent.com/16559999/170693539-f37981d6-f8dd-4706-b5db-fe771ad2c517.png)

Verder géén Moodle 4.0 issues gevonden.

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Zendesk:</div>
                <div class="panel-body" style="padding: 15px;">
                  <strong>Zendesk:&nbsp;</strong><a href="https://d3v-devopsintegration.zendesk.com/agent/tickets/507" target="_blank">507</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                  Zendesk:&nbsp;<a href="https://d3v-devopsintegration.zendesk.com/agent/tickets/507" target="_blank">#507</a>
                  <div class="pull-right" style="float:right">By: <em>DevOps Integration &lt;support@devopsintegration.io&gt;</em></div>
                </div>
              </div>

**Comment by gemguardian** [comment]
<div class="panel panel-warning" style="border-color: #faebcc;margin-bottom: 20px;background-color: #fff;border: 1px solid transparent;border-radius: 4px;-webkit-box-shadow: 0 1px 1px rgb(0 0 0 / 5%);box-shadow: 0 1px 1px rgb(0 0 0 / 5%);font-size: 14px;">
                <div class="panel-heading" style="color: #8a6d3b;background-color: #fcf8e3;border-color: #faebcc;padding: 10px 15px;border-bottom: 1px solid transparent;border-top-left-radius: 3px;border-top-right-radius: 3px;">Comment from Freshservice:</div>
                <div class="panel-body" style="padding: 15px;">
                <strong>Freshservice:&nbsp;</strong><a href="https://ltnc.freshservice.com/itil/changes/103" target="_blank">103</a>&nbsp;linked successfully.
                </div>
                <div class="panel-footer" style="padding: 10px 15px;background-color: #f5f5f5;border-top: 1px solid #ddd;border-bottom-right-radius: 3px;border-bottom-left-radius: 3px;">
                Freshservice:&nbsp;<a href="https://ltnc.freshservice.com/itil/changes/103" target="_blank">#103</a>
                  <div class="pull-right" style="float:right">By: <em>Gemma Lesterhuis &lt;gemma@ltnc.nl&gt;</em></div>
                </div>
              </div>

**Comment by vincentcornelis** [comment]
Hi Gemma,

Ik heb voor dit issue de code aangepast.

Kan je controleren of het zo naar wens werkt?

https://github.com/Lesterhuis-Training-en-Consultancy/moodle-mod_gcanvas/tree/MOODLE40

**Comment by gemguardian** [comment]
done!
